install.packages('tm', dependencies = TRUE)
install.packages('NLP')
library(NLP)

# loading required library and text
library(tm)


install.packages("gtools")
library(gtools)

#there are data files for all 4 organizations, hence the path should change for each: "UN/ALL", "WB/ALL", "WTO/ALL", "IMF/ALL"

files <- list.files(path = "WTO/ALL", full.names = TRUE)

sorted_files <- mixedsort(files)  # Sort the files naturally

texts <- Corpus(URISource(sorted_files), readerControl = list(reader = readPlain, language = "en", encoding = "UTF-8"))



memory.limit(size = 12000)  # This increases the memory limit to 16GB on Windows (adjust as needed).
print(UNstatements)
# remove(texts[[1]])
inspect(texts[[1]])


######### NOW THINGS ARE STARTING HERE TO FILTER THE CORPUS


# creating a function to remove different symbols
to_space <- content_transformer(function(x, pattern)
{ 
  return (gsub(pattern, " ", x))
}
)
# removing unwanted symbols
texts <- tm_map(texts, to_space, ":")
texts <- tm_map(texts, to_space, "-")
texts <- tm_map(texts, to_space, "'")
texts <- tm_map(texts, to_space, "'")
texts <- tm_map(texts, to_space, '"')
texts <- tm_map(texts, to_space, ";")
# removing punctuation
texts <- tm_map(texts, removePunctuation)
# transforming to lower case
texts <- tm_map(texts, content_transformer(tolower))
# removing numbers
texts <- tm_map(texts, removeNumbers)
# removing stop words (For example, in English, "the", "is" and "and)
texts <- tm_map(texts, removeWords, stopwords())
# removing white spaces
texts <- tm_map(texts, stripWhitespace)
# inspecting
# inspect(UNstatements[[1]])


library(SnowballC)
stem_docs <- tm_map(texts, stemDocument)
inspect(stem_docs[[1]])


# removing unwanted words
texts <- tm_map(texts, content_transformer(gsub), pattern = " can ", replacement = " ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " part ", replacement = " ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " important ", replacement = " ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " meaning ", replacement = " ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " thus ", replacement = " ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " understand ", replacement = " ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " set ", replacement = " ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " one ", replacement =" ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " provides ", replacement = " ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " useful ", replacement = " ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " used ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " help ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " may ", replacement = " ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " ie ", replacement = " ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " us ", replacement = " ")
# feds <- tm_map(feds, content_transformer(gsub), pattern = " ing ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " les ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " des ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " suraux ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " une ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " cent ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " girls ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " dans ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " femmes ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " much ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " que ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " take ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " par ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " los ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " notre ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " level ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " per ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " unies ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " build ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " excellencies ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " paix ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " continue ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " well ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " president ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " across ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " aux ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " nous ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " countries ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " need ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " pour ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " will ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " people ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " nations ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " general ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " must ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " secretary ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " today ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " est ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " qui ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " year ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " also ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " new ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " efforts ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " plus ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " work ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " make ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " first ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " let ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " including ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " sont ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " time ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " sur ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " one ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " first ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " many ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " thank ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " together ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " states ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " toutes ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " towards ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " high ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " call ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " avec ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " every ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " face ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " use ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " forward ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " leur ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " nous ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " monde ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " avec ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " tous ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " personnes ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " faire ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " secr?taire ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " les ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " lives ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " long ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " ces ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " uuuuu ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " years ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " role ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " droits ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " two ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " parties ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " cette ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " pays ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " ensure ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " million ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " pas ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " even ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " based ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " just ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " ont ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " see ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " needs ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " address ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " uuu ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " contre ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " devons ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " means ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " summit ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " young ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " like ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " today ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " assembly ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " now ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " member ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " end ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " systems ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " d?veloppement ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " millions ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " around ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " global ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " world ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " united ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " let ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " leurs ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " leadership ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " society ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " council ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " agenda ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " agreement ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " critical ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " national ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " durable ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " clear ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " full ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " change ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " excellencies ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " community ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " leaders ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " common ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " goals ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " nous ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " union ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " essential ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " better ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " working ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " communities ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " law ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " country ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " access ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " last ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " les ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " regional ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " international ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " support ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " les ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " life ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " social ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " let ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " day ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " way ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " governments ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\blet\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bnous\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " inclusive ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\btoday\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bthank\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bles\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bsolutions\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bimportant\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bworld\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bsystem\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bgovernment\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bopportunity\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bchallenges\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bpublic\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\beconomic\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bprogress\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " accounts ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " preliminary ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " projecting ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " budgeting ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " finally ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " sectors ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " depth ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " parallel ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " action ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " complicated ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " net ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " wages ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " planned ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " downside ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " sharper ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " sticky ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " prudently ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " modestly ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " appraisal ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " projected ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " credibility ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " published ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " three ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " discusses ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " alongside ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " management ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " require ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " space ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " explains ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " partnership ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " arrangements ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " slippages ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " krishna ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " lending ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " nominal ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " president ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " low ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " direct ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " necessary ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " regional ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " reduce ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " mail ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " accounts ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " rate ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " impact ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " extractive ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " imf ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " gdp ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " percent ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " fiscal ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " financial ", replacement = " ")
# texts <- tm_map(texts, content_transformer(gsub), pattern = " growth ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " policy ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " press ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " fund ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " monetary ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " authorities ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " board ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " economy ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " staff ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " term ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " center ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " journalists ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " site ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " bank ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " executive ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " password ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " directors ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = " measures ", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bsector\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bpolicies\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\bpress\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\wto\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\members\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\news\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\contact\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\page\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\documents\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "said\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\available\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "\\email\\b", replacement = " ")
texts <- tm_map(texts, content_transformer(gsub), pattern = "email\\b", replacement = " ")


# doc <- tm_map(doc, content_transformer(gsub), pattern = "\\blet\\b", replacement = " ")


# to add words following "inflation" for example
# texts <- tm_map(texts, content_transformer(function(x) gsub("(inflation).(\\w+)", "\\1\\2", x, ignore.case = TRUE)))

inspect(texts[40])
inspect(texts[[40]])

install.packages("RColorBrewer")
library(RColorBrewer)

install.packages("wordcloud", dependencies = TRUE)
library(wordcloud)
###################################################################
# Create a term-document matrix
tdm <- TermDocumentMatrix(texts[])

# Convert to a matrix
m <- as.matrix(tdm)

# Get word frequencies
word_freq <- sort(rowSums(m), decreasing = TRUE)


# Create the word cloud
wordcloud(names(word_freq), freq = word_freq, min.freq = 2000)

png("wordcloudWB.png", width = 1200, height = 800)
wordcloud(names(word_freq), freq = word_freq, min.freq = 1500, # WB için 200 WTO
          random.order = FALSE, colors = brewer.pal(8, "Dark2"), scale = c(4, 0.5),
          rot.per = 0.35)  # Adjust rotation percentage (0.35 allows 35% words to be vertical)

dev.off()
##########################################
